### ISSUE TITLE
ControlSystemsMTK version?

### ISSUE THREAD

**Issue by B-LIE** [JuliaControl/ControlSystemsMTK.jl#62]
I'm trying to update packages while installing Julia v1.10.2.

I notice that by installing `ControlSystemsMTK`, the package manager *down-versions* `ModelingToolkit` from v9.3 to 8.75.

**Comment by baggepinnen** [comment]
yes, ControlSystemsMTK does not yet have a release that is compatible with MTK v9. The PR that makes the update is 
- https://github.com/JuliaControl/ControlSystemsMTK.jl/pull/60

**Comment by baggepinnen** [comment]
new version out in a few minutes
